<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->pageTitle; ?></title>
    <link href="<?php echo Jobboard\APP_ROOT; ?>/public/css/bootstrap.css" rel="stylesheet">
    <!-- Custom Stylesheet by Marvin Aleman -->
    <link href="<?php echo Jobboard\APP_ROOT; ?>/public/css/nivrama.css" rel="stylesheet">
  </head>
  <body>